const quizData = [
  // ==================== 動詞・形容詞 ====================
  { genre: "動詞・形容詞", kanji: "蠢く", reading: "うごめく", meaning: "虫などがもぞもぞと動くさま。", category: "あ行" },
  { genre: "動詞・形容詞", kanji: "竦む", reading: "すくむ", meaning: "恐ろしさや緊張で体が縮んで動かなくなる。", category: "さ行" },
  { genre: "動詞・形容詞", kanji: "騙す", reading: "だます", meaning: "嘘を言って人をかつぐ。", category: "た行" },
  { genre: "動詞・形容詞", kanji: "苛む", reading: "さいなむ", meaning: "苦しめる。いじめる。", category: "さ行" },
  { genre: "動詞・形容詞", kanji: "閃く", reading: "ひらめく", meaning: "瞬間的に素晴らしい考えなどが思い浮かぶ。", category: "は行" },
  { genre: "動詞・形容詞", kanji: "佇む", reading: "たたずむ", meaning: "しばらく立ち止まっている。じっと立っている。", category: "た行" },
  { genre: "動詞・形容詞", kanji: "蹲る", reading: "うずくまる", meaning: "体を丸くしてしゃがみこむ。", category: "あ行" },
  { genre: "動詞・形容詞", kanji: "宛てる", reading: "あてる", meaning: "目当てや目標にする。割り当てる。", category: "あ行" },

  // ==================== 四字熟語 ====================
  // --- あ行 ---
  { genre: "四字熟語", kanji: "哀鴻遍野", reading: "あいこうへんや", meaning: "戦乱や災害などで流浪し、飢えや苦しみにあえぐ人々がいたるところに満ちているさま。", category: "あ行" },
  { genre: "四字熟語", kanji: "悪衣悪食", reading: "あくいあくしょく", meaning: "粗末な衣服と粗末な食べ物。また、そのような貧しい生活。", category: "あ行" },
  { genre: "四字熟語", kanji: "暗香浮動", reading: "あんこうふどう", meaning: "どこからともなく梅の花のよい香りが漂ってくるさま。", category: "あ行" },
  { genre: "四字熟語", kanji: "意気揚揚", reading: "いきようよう", meaning: "得意そうで誇らしげなさま。元気や満足感に満ちあふれているさま。", category: "あ行" },
  { genre: "四字熟語", kanji: "一言九鼎", reading: "いちげんきゅうてい", meaning: "一言の発言が九鼎（きわめて重い鼎）のように重みがあり、大きな影響力をもつこと。", category: "あ行" },
  { genre: "四字熟語", kanji: "雲心月性", reading: "うんしんげっせい", meaning: "雲や月のように、欲望に穢されず清らかでさっぱりとした心根のこと。", category: "あ行" },
  { genre: "四字熟語", kanji: "安車蒲輪", reading: "あんしゃほりん", meaning: "老人や賢者を優遇することのたとえ。蒲の葉で車輪を包んだ座り心地の良い車。", category: "あ行" },
  { genre: "四字熟語", kanji: "意気阻喪", reading: "いきそそう", meaning: "意気込みや元気が挫けて、すっかり失われてしまうこと。", category: "あ行" },
  { genre: "四字熟語", kanji: "一毫一厘", reading: "いちごういちりん", meaning: "ごくわずかな量や値のことのたとえ。", category: "あ行" },
  { genre: "四字熟語", kanji: "一闔一辟", reading: "いっこういっぺき", meaning: "ある時は閉じ、ある時は開くこと。万物の変化が絶え間ないこと。", category: "あ行" },
  { genre: "四字熟語", kanji: "阿鼻叫喚", reading: "あびきょうかん", meaning: "悲惨な状況におちいり、混乱して泣き叫ぶさま。", category: "あ行" },
  { genre: "四字熟語", kanji: "愛別離苦", reading: "あいべつりく", meaning: "親・兄弟・夫婦など、愛する者と生別・死別する苦しみのこと。", category: "あ行" },
  { genre: "四字熟語", kanji: "安貧楽道", reading: "あんぴんらくどう", meaning: "貧しい生活に甘んじながらも、自分の信じる道を楽しみ修めること。", category: "あ行" },
  { genre: "四字熟語", kanji: "意気軒昂", reading: "いきけんこう", meaning: "意気込みが盛んで、元気にあふれているさま。", category: "あ行" },
  { genre: "四字熟語", kanji: "一汁一菜", reading: "いちじゅういっさい", meaning: "汁物一品とおかず一品だけの粗末な食事のこと。", category: "あ行" },
  { genre: "四字熟語", kanji: "哀哀父母", reading: "あいあいふぼ", meaning: "子を育てる苦労を重ねてくれた父母への感謝と、死別した悲しみ。", category: "あ行" },
  { genre: "四字熟語", kanji: "握髪吐哺", reading: "あくはつとほ", meaning: "優秀な人材を求めるあまり、食事や洗髪の途中でもすぐに迎えること。", category: "あ行" },
  { genre: "四字熟語", kanji: "按兵不動", reading: "あんぺいふどう", meaning: "軍隊を進発させずにおくこと。好機を待って行動を起こさないこと。", category: "あ行" },
  { genre: "四字熟語", kanji: "一衣帯水", reading: "いちいたいすい", meaning: "一本の帯のように狭い川や海を隔てて、隣接していることのたとえ。", category: "あ行" },
  { genre: "四字熟語", kanji: "一饋十起", reading: "いっきじっき", meaning: "訪ねてくる賢者を迎えるため、一回の食事中に何度も立ち上がること。", category: "あ行" },
  { genre: "四字熟語", kanji: "一国一城", reading: "いっこくいちじょう", meaning: "一国の主として城を持つこと。他からの干渉を受けずに独立していること。", category: "あ行" },
  { genre: "四字熟語", kanji: "一気呵成", reading: "いっきかせい", meaning: "一息に文章を書き上げたり、物事を一気に仕上げたりすること。", category: "あ行" },
  { genre: "四字熟語", kanji: "一念発起", reading: "いちねんほっき", meaning: "ある事を成し遂げようと決意を固めること。", category: "あ行" },
  { genre: "四字熟語", kanji: "一網打尽", reading: "いちもうだじん", meaning: "一網で魚を全部捕えるように、悪人などを一度に全員捕まえること。", category: "あ行" },
  { genre: "四字熟語", kanji: "一目瞭然", reading: "いちもくりょうぜん", meaning: "ひと目見ただけではっきりと分かるさま。", category: "あ行" },

  // --- か行 ---
  { genre: "四字熟語", kanji: "佳人薄命", reading: "かじんはくめい", meaning: "美人にはとかく不幸な者や若死にする者が多いということ。", category: "か行" },
  { genre: "四字熟語", kanji: "夏炉冬扇", reading: "かろとうせん", meaning: "夏のいろりと冬のおうぎ。役に立たない無用なもののたとえ。", category: "か行" },
  { genre: "四字熟語", kanji: "巧言令色", reading: "こうげんれいしょく", meaning: "言葉を飾り、顔つきを繕って、人に気に入られようとすること。", category: "か行" },
  { genre: "四字熟語", kanji: "孤立無援", reading: "こりつむえん", meaning: "たった一人取り残されて、助けてくれる者が誰もいないこと。", category: "か行" },
  { genre: "四字熟語", kanji: "換骨奪胎", reading: "かんこつだったい", meaning: "古人の着想や表現を取り入れ、新しい作品を作り出すこと。", category: "か行" },
  { genre: "四字熟語", kanji: "刮目相待", reading: "かつもくそうたい", meaning: "目をこすって目を見張り、相手の進歩や成長を注意して見守ること。", category: "か行" },
  { genre: "四字熟語", kanji: "含憤蓄怨", reading: "がんふんちくえん", meaning: "怒りや怨みを心の中に溜め込むこと。", category: "か行" },
  { genre: "四字熟語", kanji: "曲学阿世", reading: "きょくがくあせい", meaning: "真理を曲げて、世間の人々や権力者に気に入られようとすること。", category: "か行" },
  { genre: "四字熟語", kanji: "錦衣玉食", reading: "きんいぎょくしょく", meaning: "贅沢な衣服を着て、おいしいごちそうを食べること。裕福な生活。", category: "か行" },
  { genre: "四字熟語", kanji: "矯角殺牛", reading: "きょうかくさつぎゅう", meaning: "欠点を直そうとして、かえって全体をだめにすることのたとえ。", category: "か行" },
  { genre: "四字熟語", kanji: "臥薪嘗胆", reading: "がしんしょうたん", meaning: "将来の復讐や成功のために、長い間の苦難に耐え忍ぶこと。", category: "か行" },
  { genre: "四字熟語", kanji: "乾坤一擲", reading: "けんこんいってき", meaning: "運命をかけて、のるかそるかの大勝負をすること。", category: "か行" },
  { genre: "四字熟語", kanji: "虚心坦懐", reading: "きょしんたんかい", meaning: "先入観や偏見を持たず、素直で平らな心で物事に対すること。", category: "か行" },
  { genre: "四字熟語", kanji: "狐仮虎威", reading: "こかこい", meaning: "他人の権力を笠に着て、威張るもののたとえ。", category: "か行" },
  { genre: "四字熟語", kanji: "苛政猛虎", reading: "かせいもうこ", meaning: "悪政は人を食べる猛虎よりも恐ろしいということ。", category: "か行" },
  { genre: "四字熟語", kanji: "苛政猛於虎", reading: "かせいもうおとら", meaning: "厳しい悪政は、人を殺す猛虎よりも恐ろしい。", category: "か行" },
  { genre: "四字熟語", kanji: "快刀乱麻", reading: "かいとうらんま", meaning: "こじれた問題や処理の難しい事態をみごとに解決すること。", category: "か行" },
  { genre: "四字熟語", kanji: "戒慎恐懼", reading: "かいしんきょうく", meaning: "己を戒め慎み、かしこまり恐れること。", category: "か行" },
  { genre: "四字熟語", kanji: "街談巷説", reading: "がいだんこうせつ", meaning: "世間のおしゃべりや流言飛語。噂話。", category: "か行" },
  { genre: "四字熟語", kanji: "画蛇添足", reading: "がだてんそく", meaning: "余計な付け足しをして、かえって台無しにすること。", category: "か行" },
  { genre: "四字熟語", kanji: "汗牛充棟", reading: "かんぎゅうじゅうとう", meaning: "蔵書が非常に多いことのたとえ。", category: "か行" },
  { genre: "四字熟語", kanji: "管鮑之交", reading: "かんぽうのこう", meaning: "利害を超えた非常に深い友情のたとえ。", category: "か行" },
  { genre: "四字熟語", kanji: "機略縦横", reading: "きりゃくじゅうおう", meaning: "計略を状況に応じて自由自在にめぐらすこと。", category: "か行" },
  { genre: "四字熟語", kanji: "奇貨可居", reading: "きかかきょ", meaning: "絶好の機会を利用して利益を得ること。", category: "か行" },
  { genre: "四字熟語", kanji: "窮鼠猫噛", reading: "きゅうそねこをかむ", meaning: "追い詰められた弱者が、強者に必死の反撃を試みること。", category: "か行" },

  // --- さ行 ---
  { genre: "四字熟語", kanji: "三尺童子", reading: "さんしゃくどうじ", meaning: "背丈が三尺ほどの幼い子供。転じて、知識や経験の浅い者のたとえ。", category: "さ行" },
  { genre: "四字熟語", kanji: "紫気東来", reading: "しきとうらい", meaning: "めでたい気（めでたい兆し）が東から漂ってくること。吉兆のたとえ。", category: "さ行" },
  { genre: "四字熟語", kanji: "山紫水明", reading: "さんしすいめい", meaning: "山や川の風景が日光に映えて、美しく清らかなさま。", category: "さ行" },
  { genre: "四字熟語", kanji: "質実剛健", reading: "しつじつごうけん", meaning: "飾り気がなく誠実で、心身ともに強くたくましいさま。", category: "さ行" },
  { genre: "四字熟語", kanji: "肆行暴戻", reading: "しこうぼうれい", meaning: "勝手気ままにふるまい、荒々しく乱暴なことをすること。", category: "さ行" },
  { genre: "四字熟語", kanji: "徙木之信", reading: "しぼくのしん", meaning: "約束を必ず守り、実行して信頼を得ることのたとえ。", category: "さ行" },
  { genre: "四字熟語", kanji: "尸位素餐", reading: "しいそさん", meaning: "職責を果たさず、無為に給料や地位を得ていること。", category: "さ行" },
  { genre: "四字熟語", kanji: "洒脱無礙", reading: "しゃだつむげ", meaning: "俗っぽさがなく、こだわりなく伸び伸びとしているさま。", category: "さ行" },
  { genre: "四字熟語", kanji: "尺短寸長", reading: "せきたんすんちょう", meaning: "人や物に長所と短所の両方があることのたとえ。", category: "さ行" },
  { genre: "四字熟語", kanji: "削足適履", reading: "さくそくてきり", meaning: "無理に物事を適合させようとして、かえって本末転倒になること。", category: "さ行" },
  { genre: "四字熟語", kanji: "三日坊主", reading: "みっかぼうず", meaning: "非常にあきっぽくて、何を始めても長続きしないことのたとえ。", category: "さ行" },
  { genre: "四字熟語", kanji: "四面楚歌", reading: "しめんそか", meaning: "周囲を敵や反対者に囲まれて、孤立無援の状態にあること。", category: "さ行" },
  { genre: "四字熟語", kanji: "自暴自棄", reading: "じぼうじき", meaning: "自分で自分を粗末にし、やけくそになること。", category: "さ行" },
  { genre: "四字熟語", kanji: "切磋琢磨", reading: "せっさたくま", meaning: "学問や精神を磨き、仲間同士でお互いを高め合うこと。", category: "さ行" },
  { genre: "四字熟語", kanji: "千載一遇", reading: "せんざいいちぐう", meaning: "千年に一度出会うかどうかの、めったにない絶好の機会。", category: "さ行" },
  { genre: "四字熟語", kanji: "左右顧眄", reading: "さゆうこめん", meaning: "ためらって周囲の様子をうかがうこと。", category: "さ行" },
  { genre: "四字熟語", kanji: "三顧之礼", reading: "さんこのれい", meaning: "目上の人が礼を尽くして賢者を何度も招くこと。", category: "さ行" },
  { genre: "四字熟語", kanji: "山千海千", reading: "さんせんかいせん", meaning: "世間の経験が豊富で、したたかで狡猾なこと。", category: "さ行" },
  { genre: "四字熟語", kanji: "自家撞着", reading: "じかどうちゃく", meaning: "自分の言動や主張の辻褄が合わないこと。", category: "さ行" },
  { genre: "四字熟語", kanji: "獅子奮迅", reading: "ししふんじん", meaning: "ライオンのように猛烈な勢いで奮闘すること。", category: "さ行" },
  { genre: "四字熟語", kanji: "自縄自縛", reading: "じじょうじばく", meaning: "自分の言葉や行動によって自分自身が動けなくなること。", category: "さ行" },
  { genre: "四字熟語", kanji: "七顛八起", reading: "しちてんはっき", meaning: "何度失敗しても諦めずに立ち上がること。", category: "さ行" },
  { genre: "四字熟語", kanji: "疾風迅雷", reading: "しっぷうじんらい", meaning: "素早く猛烈な勢いで行動することのたとえ。", category: "さ行" },
  { genre: "四字熟語", kanji: "首鼠両端", reading: "しゅそりょうたん", meaning: "どちらに付くか決めかねて、ためらっているさま。", category: "さ行" },
  { genre: "四字熟語", kanji: "神出鬼没", reading: "しんしゅつきぼつ", meaning: "自由自在に現れたり消えたりして、居場所がつかめないさま。", category: "さ行" },

  // --- た行 ---
  { genre: "四字熟語", kanji: "泰山北斗", reading: "たいざんほくと", meaning: "学問・芸術など、ある分野で第一人者として仰ぎ尊ばれる人のたとえ。", category: "た行" },
  { genre: "四字熟語", kanji: "大言壮語", reading: "たいげんそうご", meaning: "実力に見合わない大きなことを言うこと。また、その言葉。", category: "た行" },
  { genre: "四字熟語", kanji: "朝三暮四", reading: "ちょうさんぼし", meaning: "目先の違いにこだわり、結果が同じであることに気づかないこと。", category: "た行" },
  { genre: "四字熟語", kanji: "多岐亡羊", reading: "たきぼうよう", meaning: "方針が多すぎて、どれを選べばよいか迷ってしまうことのたとえ。", category: "た行" },
  { genre: "四字熟語", kanji: "断鶴続鴨", reading: "だんかくぞくおう", meaning: "自然の摂理に反して余計な手を加え、かえって害を与えることのたとえ。", category: "た行" },
  { genre: "四字熟語", kanji: "竹馬之友", reading: "ちくばのとも", meaning: "幼い頃から一緒に遊んだ、仲の良い幼なじみのこと。", category: "た行" },
  { genre: "四字熟語", kanji: "猪突猛進", reading: "ちょとつもうしん", meaning: "目標に向かって、周囲の様子を顧みず猛然と突き進むこと。", category: "た行" },
  { genre: "四字熟語", kanji: "徹頭徹尾", reading: "てっとうてつび", meaning: "最初から最後までに及んでいるさま。どこまでも貫き通すさま。", category: "た行" },
  { genre: "四字熟語", kanji: "天衣無縫", reading: "てんいむほう", meaning: "詩文などが自然で美しく、技巧の跡がないさま。無邪気で人柄が良いさま。", category: "た行" },
  { genre: "四字熟語", kanji: "徒労無益", reading: "とろうむえき", meaning: "無駄な骨折りをし、何の利益も得られないこと。", category: "た行" },
  { genre: "四字熟語", kanji: "大義名分", reading: "たいぎめいぶん", meaning: "人のとるべき道や、行動の正当な根拠。", category: "た行" },
  { genre: "四字熟語", kanji: "他山之石", reading: "たざんのいし", meaning: "他人の誤りや劣った言動も、自分の修養の参考になることのたとえ。", category: "た行" },
  { genre: "四字熟語", kanji: "単刀直入", reading: "たんとうちょくにゅう", meaning: "前置きを省いて、いきなり本題に入ること。", category: "た行" },
  { genre: "四字熟語", kanji: "知者楽水", reading: "ちしゃらくすい", meaning: "知者は真理に達しており、滞りがないので水を愛好する。", category: "た行" },
  { genre: "四字熟語", kanji: "中謀迭用", reading: "ちゅうぼうてつよう", meaning: "中の良いはかりごとを互いに採用すること。", category: "た行" },
  { genre: "四字熟語", kanji: "長目飛耳", reading: "ちょうもくひじ", meaning: "観察力が鋭く、遠くの情報を素早く集める能力。", category: "た行" },
  { genre: "四字熟語", kanji: "直情径行", reading: "ちょくじょうけいこう", meaning: "自分の感情のままにそのまま行動すること。", category: "た行" },
  { genre: "四字熟語", kanji: "痛快無比", reading: "つうかいむひ", meaning: "この上なく胸がすっとするさま。", category: "た行" },
  { genre: "四字熟語", kanji: "天涯孤独", reading: "てんがいこどく", meaning: "身寄りが一人もおらず、身一つで暮らすこと。", category: "た行" },
  { genre: "四字熟語", kanji: "当仁不譲", reading: "とうじんふじょう", meaning: "仁を行うには、どんな相手にも遠慮しないこと。", category: "た行" },

  // --- な行 ---
  { genre: "四字熟語", kanji: "南船北馬", reading: "なんせんほくば", meaning: "各地を休む間もなく忙しく旅回ることのたとえ。", category: "な行" },
  { genre: "四字熟語", kanji: "内疎外親", reading: "ないそがいしん", meaning: "心の中では嫌っているが、表面上は親しく付き合うこと。", category: "な行" },
  { genre: "四字熟語", kanji: "難兄難弟", reading: "なんけいなんてい", meaning: "二人の能力や人物が甲乙つけがたくすぐれていること。また、ともに愚かなこと。", category: "な行" },
  { genre: "四字熟語", kanji: "二枚舌", reading: "にまいじた", meaning: "矛盾したことを平気で言ったり、嘘をついたりすること。", category: "な行" },
  { genre: "四字熟語", kanji: "肉斬骨断", reading: "にくざんこつだん", meaning: "自分も傷つく覚悟で、相手に致命的な打撃を与えることのたとえ。", category: "な行" },
  { genre: "四字熟語", kanji: "日進月歩", reading: "にっしんげっぽ", meaning: "絶え間なく急速に進歩・発達すること。", category: "な行" },
  { genre: "四字熟語", kanji: "二律背反", reading: "にりつはいはん", meaning: "相反する二つの法則や主張が、ともに正当な理由をもって主張されること。", category: "な行" },
  { genre: "四字熟語", kanji: "温故知新", reading: "おんこちしん", meaning: "昔の教えや歴史を研究して、新しい知識や考え方を得ること。", category: "な行" },
  { genre: "四字熟語", kanji: "内清外直", reading: "ないせいがいちょく", meaning: "心の中が清らかで、態度がまっすぐで正直なさま。", category: "な行" },
  { genre: "四字熟語", kanji: "難攻不落", reading: "なんこうふらく", meaning: "攻めるのが難しく、容易に陥落しないこと。", category: "な行" },
  { genre: "四字熟語", kanji: "南柯之一夢", reading: "なんかのいちむ", meaning: "人生の栄華が儚いことのたとえ。", category: "な行" },
  { genre: "四字熟語", kanji: "猫鼠同眠", reading: "びょうそどうみん", meaning: "役人と悪人がグルになって悪事を働くこと。", category: "な行" },

  // --- は行 ---
  { genre: "四字熟語", kanji: "百八煩悩", reading: "ひゃくはちぼんのう", meaning: "人間にあるすべての苦しみや迷いの原因となる悩みのこと。", category: "は行" },
  { genre: "四字熟語", kanji: "波瀾万丈", reading: "はらんばんじょう", meaning: "劇的な変化や事件が多く、変化に富んでいるさま。", category: "は行" },
  { genre: "四字熟語", kanji: "蓬頭垢面", reading: "ほうとうこうめん", meaning: "髪はボサボサで顔は汚れ、身なりを全く整えていないさま。", category: "は行" },
  { genre: "四字熟語", kanji: "白砂青松", reading: "はくしゃせいしょう", meaning: "白い砂浜と緑の松林。海岸の美しい景色のたとえ。", category: "は行" },
  { genre: "四字熟語", kanji: "暴虎馮河", reading: "ぼうこひょうが", meaning: "思慮分別もなく、無謀に命がけの行動をとることのたとえ。", category: "は行" },
  { genre: "四字熟語", kanji: "八方美人", reading: "はっぽうびじん", meaning: "誰に対してもいい顔をして気に入られようとする人のこと。", category: "は行" },
  { genre: "四字熟語", kanji: "百家争鳴", reading: "ひゃっかそうめい", meaning: "多くの学問的・思想的な議論が活発に行われること。", category: "は行" },
  { genre: "四字熟語", kanji: "百発百中", reading: "ひゃっぱつひゃくちゅう", meaning: "計画や予想がすべて思い通りになることのたとえ。", category: "は行" },
  { genre: "四字熟語", kanji: "不言実行", reading: "ふげんじっこう", meaning: "あれこれ言わず、文句を言わずに黙って実行すること。", category: "は行" },
  { genre: "四字熟語", kanji: "粉骨砕身", reading: "ふんこつさいしん", meaning: "骨を粉にし、身を砕くほど一生懸命に力や心を尽くすこと。", category: "は行" },
  { genre: "四字熟語", kanji: "背水之陣", reading: "はいすいのじん", meaning: "後がない絶体絶命の状況で全力を尽くすこと。", category: "は行" },
  { genre: "四字熟語", kanji: "破竹之勢", reading: "はちくのいきおい", meaning: "猛烈な勢いでとどまることなく進むさま。", category: "は行" },
  { genre: "四字熟語", kanji: "反面教師", reading: "はんめんきょうし", meaning: "悪い手本として学ぶ対象となる人や事柄。", category: "は行" },
  { genre: "四字熟語", kanji: "悲憤慷慨", reading: "ひふんこうがい", meaning: "悲しみ憤り、悔しがってため息をつくこと。", category: "は行" },
  { genre: "四字熟語", kanji: "不撓不屈", reading: "ふとうふくつ", meaning: "どんな困難にあっても決してくじけないこと。", category: "は行" },

  // --- ま行 ---
  { genre: "四字熟語", kanji: "明鏡止水", reading: "めいきょうしすい", meaning: "邪念がなく、静かに澄み切った心境のたとえ。", category: "ま行" },
  { genre: "四字熟語", kanji: "無病息災", reading: "むびょうそくさい", meaning: "病気をせず、健康で元気なこと。", category: "ま行" },
  { genre: "四字熟語", kanji: "慢蔵誨盗", reading: "まんぞうかいとう", meaning: "財産を無防備に保管しておくと、盗賊を誘い込む原因になるということ。", category: "ま行" },
  { genre: "四字熟語", kanji: "面従腹背", reading: "めんじゅうふくはい", meaning: "表面だけ服従するふりをして、心の中では反抗すること。", category: "ま行" },
  { genre: "四字熟語", kanji: "門前雀羅", reading: "もんぜんじゃくら", meaning: "訪問客が全くなく、寂れているさまのたとえ。", category: "ま行" },
  { genre: "四字熟語", kanji: "無味乾燥", reading: "むみかんそう", meaning: "何の面白みも味わいもなく、退屈なさま。", category: "ま行" },
  { genre: "四字熟語", kanji: "茫然自失", reading: "ぼうぜんじしつ", meaning: "あっけにとられて、自分を忘れるほどボーッとしてしまうこと。", category: "ま行" },
  { genre: "四字熟語", kanji: "迷夢錯覚", reading: "めいむさっかく", meaning: "誤った考えや思い込みに囚われている状態。", category: "ま行" },
  { genre: "四字熟語", kanji: "無為自然", reading: "むいしぜん", meaning: "人為的な手を加えず、ありのままに生きること。", category: "ま行" },
  { genre: "四字熟語", kanji: "明哲保身", reading: "めいてつほしん", meaning: "賢く世の処し方を心得て、身を危険にさらさないこと。", category: "ま行" },

  // --- や行 ---
  { genre: "四字熟語", kanji: "柳緑花紅", reading: "りゅうりょくかこう", meaning: "自然のままで美しい景色のこと。また、人の手が加わっていない美しい様。", category: "や行" },
  { genre: "四字熟語", kanji: "勇往邁進", reading: "ゆうおうまいしん", meaning: "自分の目指す方へ向かって、恐れることなく突き進むこと。", category: "や行" },
  { genre: "四字熟語", kanji: "羊頭狗肉", reading: "ようとうくにく", meaning: "見かけや看板だけ立派で、内容や品質が伴わないこと。", category: "や行" },
  { genre: "四字熟語", kanji: "油断大敵", reading: "ゆだんたいてき", meaning: "油断は大きな失敗のもとになるので、絶対に気をゆるめてはならないということ。", category: "や行" },
  { genre: "四字熟語", kanji: "優柔不断", reading: "ゆうじゅうふだん", meaning: "グズグズして、物事の決断力が鈍いこと。", category: "や行" },
  { genre: "四字熟語", kanji: "悠々自適", reading: "ゆうゆうじてき", meaning: "世俗の煩わしさから離れて、自分の思い通りにのんびり暮らすこと。", category: "や行" },
  { genre: "四字熟語", kanji: "有名無実", reading: "ゆうめいむじつ", meaning: "名前だけで、それに見合う実質が伴わないこと。", category: "や行" },
  { genre: "四字熟語", kanji: "夜郎自大", reading: "やろうじだい", meaning: "自分の器量の小ささを知らずに威張ること。", category: "や行" },
  { genre: "四字熟語", kanji: "唯我独尊", reading: "ゆいがどくそん", meaning: "自分だけが優れていると思い上がること。", category: "や行" },

  // --- ら行 ---
  { genre: "四字熟語", kanji: "落花流水", reading: "らっかりゅうすい", meaning: "季節の移り変わり。または男女の情意が互いに通じ合うことのたとえ。", category: "ら行" },
  { genre: "四字熟語", kanji: "龍跳虎臥", reading: "りゅうちょうこが", meaning: "書道の筆づかいが伸びやかで力強いさまのたとえ。", category: "ら行" },
  { genre: "四字熟語", kanji: "藍田生玉", reading: "らんでんせいぎょく", meaning: "すぐれた父親から、すぐれた子が生まれることのたとえ。", category: "ら行" },
  { genre: "四字熟語", kanji: "臨機応変", reading: "りんきおうへん", meaning: "その場の状況や変化に応じて、適切な処置をとること。", category: "ら行" },
  { genre: "四字熟語", kanji: "理路整然", reading: "りろせいぜん", meaning: "文章や話のすじ道がきちんと立っているさま。", category: "ら行" },
  { genre: "四字熟語", kanji: "竜頭蛇尾", reading: "りゅうとうだび", meaning: "始めは勢いがよいが、終わりは尻すぼみになって振るわないこと。", category: "ら行" },
  { genre: "四字熟語", kanji: "老少不定", reading: "ろうしょうふじょう", meaning: "人間の寿命は予測できず、若者でもいつ死ぬかわからないということ。", category: "ら行" },

  // --- わ行 ---
  { genre: "四字熟語", kanji: "和光同塵", reading: "わこうどうじん", meaning: "自分の才能や徳を隠して、世間に目立たないように生活すること。", category: "わ行" },
  { genre: "四字熟語", kanji: "和魂洋才", reading: "わこんようさい", meaning: "日本古来の精神を守りつつ、西洋のすぐれた技術や知識を取り入れること。", category: "わ行" },
  { genre: "四字熟語", kanji: "和気藹藹", reading: "わきあいあい", meaning: "和やかな雰囲気が満ちあふれているさま。", category: "わ行" }
];